backend:
  name: github
  repo: alsawad1/Land-of-AlSawad
  branch: main

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
